import { CustomCursor } from "../../components/CustomCursor/CustomCursor";
import ThemeProvider from "../../utils/ThemeProvider/ThemeProvider";
import "./globals.css";
import {
  Krona_One,
  Lalezar,
  Maven_Pro,
  Michroma,
  Paprika,
} from "next/font/google";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

const lalezar = Lalezar({
  weight: "400",
  variable: "--font-lalezar",
});

const michroma = Michroma({
  weight: "400",
  variable: "--font-michroma",
});

const maven_pro = Maven_Pro({
  weight: "400",
  variable: "--font-maven_pro",
});

const paprika = Paprika({
  weight: "400",
  variable: "--font-paprika",
});

const krona_one = Krona_One({
  weight: "400",
  variable: "--font-krona_one",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lalezar.variable} ${michroma.variable} ${maven_pro.variable} ${paprika.variable} ${krona_one.variable} `}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
          <CustomCursor />
        </ThemeProvider>
      </body>
    </html>
  );
}
